my:
  conf:
    ip: localhost
    port: 8080
    list:
      - 101
      - 102
      - 103
    dict:
      a: a1
      b: b1
      c: c1
    状态码数组:
      - 201
      - 202
      - 203
    状态码数组2: 301,302,303
    是否启用某配置: false

# https://www.cnblogs.com/javastack/archive/2020/10/23/13862164.html